# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.GetDistance <- function(data, distance = "correlation", correlation = "pearson", checkNan = TRUE) {
    .Call('_ldt_GetDistance', PACKAGE = 'ldt', data, distance, correlation, checkNan)
}

.ClusterH <- function(distances, linkage) {
    .Call('_ldt_ClusterH', PACKAGE = 'ldt', distances, linkage)
}

.ClusterHGroup <- function(data, nGroups = 2L, threshold = 0, distance = "correlation", linkage = "single", correlation = "pearson") {
    .Call('_ldt_ClusterHGroup', PACKAGE = 'ldt', data, nGroups, threshold, distance, linkage, correlation)
}

.SearchDc <- function(y, x, w, xSizes, xPartitions, costMatrices, searchLogit, searchProbit, optimOptions, aucOptions, metricOptions, modelCheckItems, searchItems, searchOptions) {
    .Call('_ldt_SearchDc', PACKAGE = 'ldt', y, x, w, xSizes, xPartitions, costMatrices, searchLogit, searchProbit, optimOptions, aucOptions, metricOptions, modelCheckItems, searchItems, searchOptions)
}

.EstimDc <- function(y, x, w, linkFunc, newX, pcaOptionsX, costMatrices, aucOptions, simFixSize, simTrainRatio, simTrainFixSize, simSeed, weightedEval, printMsg) {
    .Call('_ldt_EstimDc', PACKAGE = 'ldt', y, x, w, linkFunc, newX, pcaOptionsX, costMatrices, aucOptions, simFixSize, simTrainRatio, simTrainFixSize, simSeed, weightedEval, printMsg)
}

.SupportsParallel <- function() {
    .Call('_ldt_SupportsParallel', PACKAGE = 'ldt')
}

.GetWeightFromMetric <- function(value, metricName) {
    .Call('_ldt_GetWeightFromMetric', PACKAGE = 'ldt', value, metricName)
}

.GetMetricFromWeight <- function(value, metricName) {
    .Call('_ldt_GetMetricFromWeight', PACKAGE = 'ldt', value, metricName)
}

.GetRoc <- function(y, scores, weights, options, printMsg) {
    .Call('_ldt_GetRoc', PACKAGE = 'ldt', y, scores, weights, options, printMsg)
}

.GetGldFromMoments <- function(mean, variance, skewness, excessKurtosis, type, s1, s2, nelderMeadOptions, printMsg) {
    .Call('_ldt_GetGldFromMoments', PACKAGE = 'ldt', mean, variance, skewness, excessKurtosis, type, s1, s2, nelderMeadOptions, printMsg)
}

.GldQuantile <- function(data, L1, L2, L3, L4) {
    .Call('_ldt_GldQuantile', PACKAGE = 'ldt', data, L1, L2, L3, L4)
}

.GldDensityQuantile <- function(data, L1, L2, L3, L4) {
    .Call('_ldt_GldDensityQuantile', PACKAGE = 'ldt', data, L1, L2, L3, L4)
}

.CombineStats4 <- function(list1, list2) {
    .Call('_ldt_CombineStats4', PACKAGE = 'ldt', list1, list2)
}

.GetPca <- function(x, center, scale, newX) {
    .Call('_ldt_GetPca', PACKAGE = 'ldt', x, center, scale, newX)
}

.SearchSur <- function(y, x, numTargets, xSizes, xPartitions, numFixXPartitions, yGroups, searchSigMaxIter, searchSigMaxProb, metricOptions, modelCheckItems, searchItems, searchOptions) {
    .Call('_ldt_SearchSur', PACKAGE = 'ldt', y, x, numTargets, xSizes, xPartitions, numFixXPartitions, yGroups, searchSigMaxIter, searchSigMaxProb, metricOptions, modelCheckItems, searchItems, searchOptions)
}

.EstimSur <- function(y, x, addIntercept, searchSigMaxIter, searchSigMaxProb, restriction, newX, pcaOptionsY, pcaOptionsX, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber, printMsg) {
    .Call('_ldt_EstimSur', PACKAGE = 'ldt', y, x, addIntercept, searchSigMaxIter, searchSigMaxProb, restriction, newX, pcaOptionsY, pcaOptionsX, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber, printMsg)
}

.SearchVarma <- function(y, x, numTargets, ySizes, yPartitions, xGroups, maxParams, seasonsCount, maxHorizon, newX, simUsePreviousEstim, olsStdMultiplier, lbfgsOptions, metricOptions, modelCheckItems, searchItems, searchOptions) {
    .Call('_ldt_SearchVarma', PACKAGE = 'ldt', y, x, numTargets, ySizes, yPartitions, xGroups, maxParams, seasonsCount, maxHorizon, newX, simUsePreviousEstim, olsStdMultiplier, lbfgsOptions, metricOptions, modelCheckItems, searchItems, searchOptions)
}

.EstimVarma <- function(y, x, params, seasonsCount, addIntercept, lbfgsOptions, olsStdMultiplier, pcaOptionsY, pcaOptionsX, maxHorizon, newX, simFixSize, simHorizons, simUsePreviousEstim, simMaxConditionNumber, printMsg) {
    .Call('_ldt_EstimVarma', PACKAGE = 'ldt', y, x, params, seasonsCount, addIntercept, lbfgsOptions, olsStdMultiplier, pcaOptionsY, pcaOptionsX, maxHorizon, newX, simFixSize, simHorizons, simUsePreviousEstim, simMaxConditionNumber, printMsg)
}

