# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.GetDistance <- function(data, distance = "correlation", correlation = "pearson", checkNan = TRUE) {
    .Call('_ldt_GetDistance', PACKAGE = 'ldt', data, distance, correlation, checkNan)
}

.ClusterH <- function(distances, linkage) {
    .Call('_ldt_ClusterH', PACKAGE = 'ldt', distances, linkage)
}

.ClusterHGroup <- function(data, nGroups = 2L, threshold = 0, distance = "correlation", linkage = "single", correlation = "pearson") {
    .Call('_ldt_ClusterHGroup', PACKAGE = 'ldt', data, nGroups, threshold, distance, linkage, correlation)
}

.SearchDc <- function(data, combinations, metrics, modelChecks, items, options, costMatrices, searchLogit, searchProbit, newtonOptions, aucOptions, numChoices) {
    .Call('_ldt_SearchDc', PACKAGE = 'ldt', data, combinations, metrics, modelChecks, items, options, costMatrices, searchLogit, searchProbit, newtonOptions, aucOptions, numChoices)
}

.EstimDc <- function(data, linkFunc, pcaOptionsX, costMatrices, newtonOptions, aucOptions, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber, numChoices, weightedEval) {
    .Call('_ldt_EstimDc', PACKAGE = 'ldt', data, linkFunc, pcaOptionsX, costMatrices, newtonOptions, aucOptions, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber, numChoices, weightedEval)
}

.SearchRFunc <- function(data, combinations, metrics, modelChecks, items, options, rFuncName, length1, isInnerExogenous) {
    .Call('_ldt_SearchRFunc', PACKAGE = 'ldt', data, combinations, metrics, modelChecks, items, options, rFuncName, length1, isInnerExogenous)
}

.SupportsParallel <- function() {
    .Call('_ldt_SupportsParallel', PACKAGE = 'ldt')
}

.GetWeightFromMetric <- function(value, metricName, minValue) {
    .Call('_ldt_GetWeightFromMetric', PACKAGE = 'ldt', value, metricName, minValue)
}

.GetMetricFromWeight <- function(value, metricName, minValue) {
    .Call('_ldt_GetMetricFromWeight', PACKAGE = 'ldt', value, metricName, minValue)
}

.GetRoc <- function(y, scores, weights, options) {
    .Call('_ldt_GetRoc', PACKAGE = 'ldt', y, scores, weights, options)
}

.GetGldFromMoments <- function(mean, variance, skewness, excessKurtosis, type, s1, s2, nelderMeadOptions) {
    .Call('_ldt_GetGldFromMoments', PACKAGE = 'ldt', mean, variance, skewness, excessKurtosis, type, s1, s2, nelderMeadOptions)
}

.GldQuantile <- function(data, L1, L2, L3, L4) {
    .Call('_ldt_GldQuantile', PACKAGE = 'ldt', data, L1, L2, L3, L4)
}

.GldDensityQuantile <- function(data, L1, L2, L3, L4) {
    .Call('_ldt_GldDensityQuantile', PACKAGE = 'ldt', data, L1, L2, L3, L4)
}

.CombineStats4 <- function(list1, list2) {
    .Call('_ldt_CombineStats4', PACKAGE = 'ldt', list1, list2)
}

.GetPca <- function(x, center, scale, newX) {
    .Call('_ldt_GetPca', PACKAGE = 'ldt', x, center, scale, newX)
}

.SearchSur <- function(data, combinations, metrics, modelChecks, items, options, searchSigMaxIter, searchSigMaxProb) {
    .Call('_ldt_SearchSur', PACKAGE = 'ldt', data, combinations, metrics, modelChecks, items, options, searchSigMaxIter, searchSigMaxProb)
}

.EstimSur <- function(data, searchSigMaxIter, searchSigMaxProb, restriction, pcaOptionsY, pcaOptionsX, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber) {
    .Call('_ldt_EstimSur', PACKAGE = 'ldt', data, searchSigMaxIter, searchSigMaxProb, restriction, pcaOptionsY, pcaOptionsX, simFixSize, simTrainRatio, simTrainFixSize, simSeed, simMaxConditionNumber)
}

.SearchVarma <- function(data, combinations, metrics, modelChecks, items, options, maxParams, seasonsCount, maxHorizon, simUsePreviousEstim, olsStdMultiplier, lbfgsOptions) {
    .Call('_ldt_SearchVarma', PACKAGE = 'ldt', data, combinations, metrics, modelChecks, items, options, maxParams, seasonsCount, maxHorizon, simUsePreviousEstim, olsStdMultiplier, lbfgsOptions)
}

.EstimVarma <- function(data, params, seasonsCount, lbfgsOptions, olsStdMultiplier, pcaOptionsY, pcaOptionsX, maxHorizon, simFixSize, simHorizons, simUsePreviousEstim, simMaxConditionNumber) {
    .Call('_ldt_EstimVarma', PACKAGE = 'ldt', data, params, seasonsCount, lbfgsOptions, olsStdMultiplier, pcaOptionsY, pcaOptionsX, maxHorizon, simFixSize, simHorizons, simUsePreviousEstim, simMaxConditionNumber)
}

